Bike/src/bike/urls.py
from django.urls import path

from bike.views import rentview, adminbikeview, CreateBike, EditBike, DeleteBike, rentfilterview

urlpatterns = [
    path('rentpage/', rentview, name='rentpage'),
    path('bike-type-page/<uuid:id>', rentfilterview, name='bike-type-page'),
    path('bike_admin/', adminbikeview, name='bike_admin'),
    path('add_bike/', CreateBike.as_view(), name='add_bike'),
    path('edit-bike/<uuid:pk>', EditBike.as_view(), name='update_bike'),
    path('delete-bike/<uuid:pk>', DeleteBike.as_view(), name='delete_bike'),
]

Bike/src/core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core import views, settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('', include('posts.urls')),
    path('', include('bike.urls')),
    path('', include('orders.urls')),
    path('adminpage', views.adminpage, name='adminpage'),
    path('', views.home, name='home'),
    path('about-us/', views.about, name='about'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bike/src/bike/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from login.models import CustomUser


class Type(models.Model):
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, unique=True
    )
    name = models.CharField(max_length=255)
    price = models.IntegerField(blank=True)

    class Meta:
        db_table = "type"

    def __str__(self):
        return self.name


class Bike(models.Model):
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, unique=True
    )
    name = models.CharField(max_length=255)
    type = models.ForeignKey(Type, related_name="bike", on_delete=models.SET_NULL, null=True)
    license_plate = models.CharField(max_length=255, blank=True)
    image = models.ImageField(
        _("Image"), upload_to="bike/", blank=True, null=True
    )
    status = models.BooleanField(default=True)

    class Meta:
        db_table = "bike"

    def __str__(self):
        if self.status:
            status = 'True'
        else:
            status = 'False'
        return self.name + ' | ' + status

    def get_absolute_url(self):
        return reverse('bike_admin')


class Evaluate(models.Model):
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, unique=True
    )
    content = models.TextField(blank=True)
    starts = models.IntegerField(blank=True)
    bike = models.ForeignKey(Bike, related_name="bike", on_delete=models.SET_NULL, null=True)
    customer = models.ForeignKey(CustomUser, related_name="bike", on_delete=models.SET_NULL, null=True)

    class Meta:
        db_table = "evaluate"

Bike/src/bike/forms.py
from django import forms
from bike.models import Bike


class BikeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['type'].widget.attrs.update({'class': 'form-control'})
        self.fields['license_plate'].widget.attrs.update({'class': 'form-control'})
        self.fields['image'].widget.attrs.update({'class': 'form-control'})
        self.fields['status'].widget.attrs.update({'class': 'form-check-input ml-4'})

    class Meta:
        model = Bike
        fields = ('name', 'type', 'license_plate', 'image', 'status')

Bike/src/bike/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render
from bike.models import Bike, Type
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import UpdateView, DeleteView, DetailView
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy
from bike.forms import BikeForm


# Create your views here.


def rentview(request):
    bikes = Bike.objects.all()
    types = Type.objects.all()
    return render(request, 'core/bike/rentpage.html', {'bikes': bikes, 'types': types})


def rentfilterview(request, *args, **kwargs):
    type_id = kwargs['id']
    bikes = Bike.objects.filter(type__id=type_id)
    types = Type.objects.all()
    return render(request, 'core/bike/filter_bike_page.html', {'bikes': bikes, 'types': types})


@staff_member_required
def adminbikeview(request):
    bikes = Bike.objects.all()

    class Meta:
        ordering = ['name']
    return render(request, 'core/bike/bikes_admin.html', {'bikes': bikes})



class CreateBike(PermissionRequiredMixin, View):
    permission_required = 'login.login'

    def get(self, request):
        form = BikeForm()
        if request.user.is_staff:
            return render(request, 'core/bike/add_bike.html', {'form': form})
        else:
            return render(request, 'core/404.html')


    def post(self, request):
        form = BikeForm(request.POST, request.FILES)
        print(request.FILES)
        if form.is_valid():
            bike = Bike(
                name=form.cleaned_data['name'],
                type=form.cleaned_data['type'],
                license_plate=form.cleaned_data['license_plate'],
                image=form.cleaned_data['image']
            )
            bike.save()

        bikes = Bike.objects.all()
        if request.user.is_staff:
            return render(request, 'core/bike/bikes_admin.html', {'bikes': bikes})
        else:
            return render(request, 'core/404.html')



class EditBike(PermissionRequiredMixin, View):
    permission_required = 'login.login'

    def get(self, request, *args, **kwargs):
        id = kwargs['pk']
        bike = Bike.objects.get(id=id)
        types = Type.objects.all()
        return render(request, 'core/bike/edit_bike.html', {'bike': bike, 'types': types})


    def post(self, request, *args, **kwargs):
        print(self, request, args, kwargs)
        id = kwargs['pk']
        bike = Bike.objects.get(id=id)
        form = BikeForm(request.POST, request.FILES)

        if form.is_valid():
            print(form.cleaned_data['image'])
            bike.name = form.cleaned_data['name']
            bike.type_name = Type.objects.get(name=form.cleaned_data['type'])
            bike.license_plate = form.cleaned_data['license_plate']
            if form.cleaned_data['image'] != None:
                bike.image = form.cleaned_data['image']
            else:
                bike.image = bike.image
            bike.status = form.cleaned_data['status']
            bike.save()
        bikes = Bike.objects.all()
        if request.user.is_staff:
            return render(request, 'core/bike/bikes_admin.html', {'bikes': bikes})
        else:
            return render(request, 'core/404.html')



class DeleteBike(PermissionRequiredMixin, DeleteView):
    permission_required = 'login.login'
    model = Bike
    template_name = 'core/bike/delete_bike.html'
    success_url = reverse_lazy('bike_admin')

Bike/src/core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from bike.models import Type, Bike, Evaluate, CustomUser
# Create your views here.


# @login_required(login_url='login')
def home(request):
    types = Type.objects.all()
    return render(request, 'core/index.html', {'types': types})


def about(request):
    types = Type.objects.all()
    return render(request, 'core/about_us.html', {'types': types})

def adminpage(request):
    types = Type.objects.all()
    bikes = Bike.objects.all()
    customers = CustomUser.objects.all()
    evalutes = Evaluate.objects.all()
    if request.user.is_staff:
        return render(request, 'core/admin.html', {'types': types, 'bikes': bikes, 'customers':  customers, 'evalutes': evalutes})
    else:
        return render(request, 'core/404.html')

Bike/src/templates/core/bike/add_bike.html
{% extends 'core/admin.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <h1>Thêm xe</h1>
        <div class="form-group">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Thêm</button>
            <a href="{% url 'bike_admin' %}" class="btn btn-primary">Quay lại quản lý xe</a>
        </form>
        </div>
    </div>

{% endblock %}

Bike/src/templates/core/bike/bikes_admin.html
{% extends 'core/admin.html' %}
{% load static %}
{% block content %}
<div class="rent">
    <a href="{% url 'add_bike' %}" class="btn btn-primary mb-5">Thêm Xe</a>
    <div class="row">
        {% for bike in bikes %}
        <div class="card mr-2" style="width: 16rem; height: 472px;">
            {% if bike.image %}
                <img src="{{ bike.image.url }}" class="card-img-top" alt="bike">
            {% endif %}
            <div class="card-body">
                <a href="#" class="card-title">{{ bike.name }}</a>
                <p class="card-text">{{ bike.type }}</p>
                <p class="card-text">{{ bike.license_plate }}</p>
                <p class="card-text">{{ bike.type.price }}đ</p>
                <p class="card-text">
                    {% if bike.status %}
                        Active
                    {% else %}
                        Not Active
                    {% endif %}
                </p>
                <div class="d-flex align-items-center mt-4 mb-0">
                    <a class="btn btn-primary mr-3" href="{% url 'update_bike' bike.id %}">Sửa</a>
                    <a class="btn btn-primary" href="{% url 'delete_bike' bike.id %}">Xóa</a>
                </div>
            </div>
        </div>

        {% endfor %}

    </div>
</div>

{% endblock %}

Bike/src/templates/core/bike/delete_bike.html
{% extends 'core/admin.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <h1>Xóa xe</h1>
        <div class="form-group">
        <form method="post">
            {% csrf_token %}
            <h3 class="h3 title">Xóa xe: {{ bike.name }} | BS: {{ bike.license_plate}}</h3>

            <strong>Bạn có chắc không?</strong>
            <button type="submit" class="btn btn-danger">Xóa</button>
            <a href="{% url 'bike_admin' %}" class="btn btn-primary">Quay lại</a>
        </form>
        </div>
    </div>

{% endblock %}

Bike/src/templates/core/bike/edit_bike.html
{% extends 'core/admin.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h1>Sửa chi tiết xe</h1>
    <div class="form-group">
        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <p>
                <label for="id_name">Name:</label>
                <input type="text" name="name" maxlength="255" class="form-control" required="" id="id_name" value="{{ bike.name }}">
            </p>
            <p>
                <label for="id_type">Type:</label>
                <select name="type" class="form-control" required="" id="id_type">
                    {% for type in types %}
                        {% if bike.type.id == type.id %}
                            <option value="{{ type.id }}" selected>{{ type.name }}</option>
                        {% else %}
                            <option value="{{ type.id }}">{{ type.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </p>
            <p>
                <label for="id_license_plate">License plate:</label>
                <input type="text" name="license_plate" maxlength="255" class="form-control" id="id_license_plate" value="{{ bike.license_plate }}">
            </p>
            <p>
                <label for="id_image">Image:</label>
                <a href="/media/{{ bike.image }}">{{ bike.image }}</a>
                <input type="file" name="image" accept="image/*" class="form-control" id="id_image">
            </p>
            <p>
                <label for="id_status">Status:</label>
                <input type="checkbox" name="status" class="form-check-input ml-4" id="id_status">
            </p>
            <button type="submit" class="btn btn-primary">Sửa</button>
            <a href="{% url 'bike_admin' %}" class="btn btn-primary">Quay lại</a>
        </form>
    </div>
</div>
<script>
    function status_check() {
      document.getElementById("id_status").checked = true;
    }
    function status_nocheck() {
      document.getElementById("id_status").checked = false;
    }
    {% if bike.status %}
        status_check();
    {% else %}
        status_nocheck();
    {% endif %}

</script>
{% endblock %}

Bike/src/templates/core/bike/filter_bike_page.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
<div class="container pt-4 pb-4">
    <div class="row">
        <div class="rent row">
            <div class="rent-filters col-4">
                <div class="rent-filter rent-filter-day">
                    <h5>Ngày thuê</h5>
                    <input type="datetime-local">
                </div>
                <div class="rent-filter rent-filter-day">
                    <h5>Ngày trả</h5>
                    <input type="datetime-local">
                </div>
                <div class="rent-filter rent-filter-name">
                    <h5>Nhập tên xe</h5>
                    <input type="text">
                </div>
                <div class="rent-filter rent-filter-type">
                    <h5>Loại xe</h5>
                    <select id="type-bike">
                        <option value="0">---Chọn---</option>
                        {% for type in types %}
                            <option value="{{ type.id }}">{{ type.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="rent-filter rent-filter-submit">
                    <input type="submit" value="Tìm" class="btn btn-info btn-rent-submit">
                </div>
            </div>
            <div class="rent-list-container col-8">
                <div class="rent-list-filter">
                    <select id="filter-price">
                        <option value="0">---Chọn---</option>
                        <option value="1">Giảm dần</option>
                        <option value="2">Tăng dần</option>
                    </select>
                </div>
                <div class="rent-list-bikes">
                    {% for bike in bikes %}
                        {% if bike.status %}
                        <div class="rent-item">
                            <div class="item-img">
                                {% if bike.image %}
                                    <img src="{{ bike.image.url }}" class="img-product"></img>
                                {% endif %}
                            </div>
                            <div class="item-about">
                                <a href="#">{{ bike.name }}</a>
                                <p>{{ bike.type }}</p>
                            </div>
                            <div class="item-rent">
                                <h4>{{ bike.type.price }}đ</h4>
                                <a href="{% url 'rent-bike' bike.id %}" class="btn btn-info">Thuê xe</a>
                            </div>
                        </div>
                        {% endif %}
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Bike/src/templates/core/bike/rentpage.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
<div class="container pt-4 pb-4">
    <div class="row">
        <div class="rent row">
            <div class="rent-filters col-4">
                <div class="rent-filter rent-filter-day">
                    <h5>Ngày thuê</h5>
                    <input type="datetime-local">
                </div>
                <div class="rent-filter rent-filter-day">
                    <h5>Ngày trả</h5>
                    <input type="datetime-local">
                </div>
                <div class="rent-filter rent-filter-name">
                    <h5>Nhập tên xe</h5>
                    <input type="text">
                </div>
                <div class="rent-filter rent-filter-type">
                    <h5>Loại xe</h5>
                    <select id="type-bike">
                        <option value="0">---Chọn---</option>
                        {% for type in types %}
                            <option value="{{ type.id }}">{{ type.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="rent-filter rent-filter-submit">
                    <input type="submit" value="Tìm" class="btn btn-info btn-rent-submit">
                </div>
            </div>
            <div class="rent-list-container col-8">
                <div class="rent-list-filter">
                    <select id="filter-price">
                        <option value="0">---Chọn---</option>
                        <option value="1">Giảm dần</option>
                        <option value="2">Tăng dần</option>
                    </select>
                </div>
                <div class="rent-list-bikes">
                    {% for bike in bikes %}
                        {% if bike.status %}
                        <div class="rent-item">
                            <div class="item-img">
                                {% if bike.image %}
                                    <img src="{{ bike.image.url }}" class="img-product"></img>
                                {% endif %}
                            </div>
                            <div class="item-about">
                                <a href="#">{{ bike.name }}</a>
                                <p>{{ bike.type }}</p>
                            </div>
                            <div class="item-rent">
                                <h4>{{ bike.type.price }}đ</h4>
                                <a href="{% url 'rent-bike' bike.id %}" class="btn btn-info">Thuê xe</a>
                            </div>
                        </div>
                        {% endif %}
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}